/* eslint-disable */
// This file is auto-generated by `npm run gen:supabase-types`.
// Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      app_faqs: {
        Row: {
          answer_html: string
          created_at: string
          created_by: string | null
          id: string
          is_active: boolean
          question: string
          sort_order: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          answer_html?: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          question: string
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          answer_html?: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          question?: string
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      app_legal_documents: {
        Row: {
          content_html: string
          created_at: string
          slug: string
          title: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          content_html?: string
          created_at?: string
          slug: string
          title: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          content_html?: string
          created_at?: string
          slug?: string
          title?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      app_support_settings: {
        Row: {
          created_at: string
          id: number
          updated_at: string
          updated_by: string | null
          whatsapp_url: string | null
        }
        Insert: {
          created_at?: string
          id?: number
          updated_at?: string
          updated_by?: string | null
          whatsapp_url?: string | null
        }
        Update: {
          created_at?: string
          id?: number
          updated_at?: string
          updated_by?: string | null
          whatsapp_url?: string | null
        }
        Relationships: []
      }
      chat_messages: {
        Row: {
          content: string
          created_at: string
          id: string
          is_read: boolean
          message_type: string
          room_id: string
          sender_id: string | null
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          is_read?: boolean
          message_type?: string
          room_id: string
          sender_id?: string | null
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          is_read?: boolean
          message_type?: string
          room_id?: string
          sender_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "chat_messages_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "chat_room_summaries"
            referencedColumns: ["room_id"]
          },
          {
            foreignKeyName: "chat_messages_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "chat_rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_rooms: {
        Row: {
          created_at: string
          id: string
          landlord_id: string
          listing_id: string
          tenant_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          landlord_id: string
          listing_id: string
          tenant_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          landlord_id?: string
          listing_id?: string
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "chat_rooms_landlord_id_fkey"
            columns: ["landlord_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_rooms_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listing_moderation_queue"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_rooms_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kyc_submissions: {
        Row: {
          created_at: string
          document_back_url: string | null
          document_front_url: string | null
          document_number: string
          document_type: string
          full_name: string
          id: string
          phone: string
          property_document_url: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          reviewer_note: string | null
          risk_score: number
          selfie_url: string | null
          status: string
          submitted_at: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          document_back_url?: string | null
          document_front_url?: string | null
          document_number: string
          document_type: string
          full_name: string
          id?: string
          phone: string
          property_document_url?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewer_note?: string | null
          risk_score?: number
          selfie_url?: string | null
          status?: string
          submitted_at?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          document_back_url?: string | null
          document_front_url?: string | null
          document_number?: string
          document_type?: string
          full_name?: string
          id?: string
          phone?: string
          property_document_url?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          reviewer_note?: string | null
          risk_score?: number
          selfie_url?: string | null
          status?: string
          submitted_at?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      listing_moderation_queue: {
        Row: {
          amenity_tags: string[]
          carpet_area_sqft: number | null
          created_at: string
          currency_code: string
          description: string
          district_id: string | null
          facing: string | null
          furnishing_status: string | null
          id: string
          is_featured: boolean
          is_negotiable: boolean
          is_rented: boolean
          is_story: boolean
          landlord_is_verified: boolean
          landlord_name: string
          landlord_phone: string
          latitude: number | null
          listed_by: string | null
          location_text: string
          longitude: number | null
          moderated_at: string | null
          moderated_by: string | null
          moderator_note: string | null
          municipality_id: string | null
          photo_urls: string[]
          price: number
          property_category: string
          property_floor_no: number | null
          property_title: string
          security_deposit: boolean | null
          security_deposit_amount: number | null
          show_exact_location: boolean
          source_listing_id: string | null
          state_id: string | null
          status: string
          subcategory: string | null
          submitted_at: string
          thumbnail_url: string | null
          total_area_sqft: number | null
          total_floor: number | null
          updated_at: string
          ward_id: string | null
        }
        Insert: {
          amenity_tags?: string[]
          carpet_area_sqft?: number | null
          created_at?: string
          currency_code?: string
          description: string
          district_id?: string | null
          facing?: string | null
          furnishing_status?: string | null
          id?: string
          is_featured?: boolean
          is_negotiable?: boolean
          is_rented?: boolean
          is_story?: boolean
          landlord_is_verified?: boolean
          landlord_name: string
          landlord_phone: string
          latitude?: number | null
          listed_by?: string | null
          location_text: string
          longitude?: number | null
          moderated_at?: string | null
          moderated_by?: string | null
          moderator_note?: string | null
          municipality_id?: string | null
          photo_urls?: string[]
          price: number
          property_category: string
          property_floor_no?: number | null
          property_title: string
          security_deposit?: boolean | null
          security_deposit_amount?: number | null
          show_exact_location?: boolean
          source_listing_id?: string | null
          state_id?: string | null
          status?: string
          subcategory?: string | null
          submitted_at?: string
          thumbnail_url?: string | null
          total_area_sqft?: number | null
          total_floor?: number | null
          updated_at?: string
          ward_id?: string | null
        }
        Update: {
          amenity_tags?: string[]
          carpet_area_sqft?: number | null
          created_at?: string
          currency_code?: string
          description?: string
          district_id?: string | null
          facing?: string | null
          furnishing_status?: string | null
          id?: string
          is_featured?: boolean
          is_negotiable?: boolean
          is_rented?: boolean
          is_story?: boolean
          landlord_is_verified?: boolean
          landlord_name?: string
          landlord_phone?: string
          latitude?: number | null
          listed_by?: string | null
          location_text?: string
          longitude?: number | null
          moderated_at?: string | null
          moderated_by?: string | null
          moderator_note?: string | null
          municipality_id?: string | null
          photo_urls?: string[]
          price?: number
          property_category?: string
          property_floor_no?: number | null
          property_title?: string
          security_deposit?: boolean | null
          security_deposit_amount?: number | null
          show_exact_location?: boolean
          source_listing_id?: string | null
          state_id?: string | null
          status?: string
          subcategory?: string | null
          submitted_at?: string
          thumbnail_url?: string | null
          total_area_sqft?: number | null
          total_floor?: number | null
          updated_at?: string
          ward_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "listing_moderation_queue_district_id_fkey"
            columns: ["district_id"]
            isOneToOne: false
            referencedRelation: "master_districts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_moderation_queue_municipality_id_fkey"
            columns: ["municipality_id"]
            isOneToOne: false
            referencedRelation: "master_municipalities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_moderation_queue_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "master_states"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_moderation_queue_ward_id_fkey"
            columns: ["ward_id"]
            isOneToOne: false
            referencedRelation: "master_wards"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_view_events: {
        Row: {
          id: string
          listing_id: string
          source: string
          viewed_at: string
          viewer_user_id: string | null
        }
        Insert: {
          id?: string
          listing_id: string
          source?: string
          viewed_at?: string
          viewer_user_id?: string | null
        }
        Update: {
          id?: string
          listing_id?: string
          source?: string
          viewed_at?: string
          viewer_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "listing_view_events_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listing_moderation_queue"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_view_stats: {
        Row: {
          last_viewed_at: string | null
          listing_id: string
          total_views: number
          unique_viewers: number
        }
        Insert: {
          last_viewed_at?: string | null
          listing_id: string
          total_views?: number
          unique_viewers?: number
        }
        Update: {
          last_viewed_at?: string | null
          listing_id?: string
          total_views?: number
          unique_viewers?: number
        }
        Relationships: [
          {
            foreignKeyName: "listing_view_stats_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: true
            referencedRelation: "listing_moderation_queue"
            referencedColumns: ["id"]
          },
        ]
      }
      master_amenities: {
        Row: {
          category_id: string
          code: string
          created_at: string
          description: string | null
          display_order: number
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          category_id: string
          code: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          category_id?: string
          code?: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "master_amenities_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "master_amenity_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      master_amenity_categories: {
        Row: {
          code: string
          created_at: string
          description: string | null
          display_order: number
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      master_countries: {
        Row: {
          code: string
          created_at: string
          id: string
          is_active: boolean
          latitude: number | null
          longitude: number | null
          name: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          name: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      master_districts: {
        Row: {
          code: string
          created_at: string
          id: string
          is_active: boolean
          latitude: number | null
          longitude: number | null
          name: string
          state_id: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          name: string
          state_id: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          name?: string
          state_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "master_districts_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "master_states"
            referencedColumns: ["id"]
          },
        ]
      }
      master_municipalities: {
        Row: {
          code: string
          created_at: string
          district_id: string
          id: string
          is_active: boolean
          latitude: number | null
          longitude: number | null
          municipality_type: string
          name: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          district_id: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          municipality_type: string
          name: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          district_id?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          municipality_type?: string
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "master_municipalities_district_id_fkey"
            columns: ["district_id"]
            isOneToOne: false
            referencedRelation: "master_districts"
            referencedColumns: ["id"]
          },
        ]
      }
      master_price_range_configs: {
        Row: {
          config_key: string
          created_at: string
          currency_code: string
          id: string
          is_active: boolean
          label: string
          max_value: number
          min_value: number
          step_value: number
          updated_at: string
        }
        Insert: {
          config_key: string
          created_at?: string
          currency_code?: string
          id?: string
          is_active?: boolean
          label: string
          max_value: number
          min_value: number
          step_value: number
          updated_at?: string
        }
        Update: {
          config_key?: string
          created_at?: string
          currency_code?: string
          id?: string
          is_active?: boolean
          label?: string
          max_value?: number
          min_value?: number
          step_value?: number
          updated_at?: string
        }
        Relationships: []
      }
      master_property_categories: {
        Row: {
          code: string
          created_at: string
          description: string | null
          display_order: number
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      master_property_subcategories: {
        Row: {
          bedroom_count: number | null
          category_id: string
          code: string
          created_at: string
          description: string | null
          display_order: number
          id: string
          is_active: boolean
          name: string
          updated_at: string
        }
        Insert: {
          bedroom_count?: number | null
          category_id: string
          code: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          bedroom_count?: number | null
          category_id?: string
          code?: string
          created_at?: string
          description?: string | null
          display_order?: number
          id?: string
          is_active?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "master_property_subcategories_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "master_property_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      master_states: {
        Row: {
          code: string
          country_id: string
          created_at: string
          id: string
          is_active: boolean
          latitude: number | null
          longitude: number | null
          name: string
          updated_at: string
        }
        Insert: {
          code: string
          country_id: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          name: string
          updated_at?: string
        }
        Update: {
          code?: string
          country_id?: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "master_states_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "master_countries"
            referencedColumns: ["id"]
          },
        ]
      }
      master_translation_keys: {
        Row: {
          created_at: string
          default_text: string
          description: string | null
          id: string
          is_active: boolean
          key: string
          namespace: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          default_text: string
          description?: string | null
          id?: string
          is_active?: boolean
          key: string
          namespace: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          default_text?: string
          description?: string | null
          id?: string
          is_active?: boolean
          key?: string
          namespace?: string
          updated_at?: string
        }
        Relationships: []
      }
      master_translation_values: {
        Row: {
          created_at: string
          id: string
          locale_code: string
          translation_key_id: string
          updated_at: string
          value: string
        }
        Insert: {
          created_at?: string
          id?: string
          locale_code: string
          translation_key_id: string
          updated_at?: string
          value: string
        }
        Update: {
          created_at?: string
          id?: string
          locale_code?: string
          translation_key_id?: string
          updated_at?: string
          value?: string
        }
        Relationships: [
          {
            foreignKeyName: "master_translation_values_translation_key_id_fkey"
            columns: ["translation_key_id"]
            isOneToOne: false
            referencedRelation: "master_translation_keys"
            referencedColumns: ["id"]
          },
        ]
      }
      master_wards: {
        Row: {
          code: string
          created_at: string
          id: string
          is_active: boolean
          latitude: number | null
          longitude: number | null
          municipality_id: string
          name: string | null
          updated_at: string
          ward_number: number
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          municipality_id: string
          name?: string | null
          updated_at?: string
          ward_number: number
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          latitude?: number | null
          longitude?: number | null
          municipality_id?: string
          name?: string | null
          updated_at?: string
          ward_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "master_wards_municipality_id_fkey"
            columns: ["municipality_id"]
            isOneToOne: false
            referencedRelation: "master_municipalities"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_events: {
        Row: {
          actor_id: string | null
          body: string
          category_id: string | null
          created_at: string
          data: Json
          event_type: string
          expires_at: string | null
          id: string
          is_read: boolean
          push_error: string | null
          push_receipt_id: string | null
          push_status: string
          push_ticket_id: string | null
          read_at: string | null
          recipient_id: string
          route: string | null
          sent_at: string | null
          title: string
        }
        Insert: {
          actor_id?: string | null
          body: string
          category_id?: string | null
          created_at?: string
          data?: Json
          event_type: string
          expires_at?: string | null
          id?: string
          is_read?: boolean
          push_error?: string | null
          push_receipt_id?: string | null
          push_status?: string
          push_ticket_id?: string | null
          read_at?: string | null
          recipient_id: string
          route?: string | null
          sent_at?: string | null
          title: string
        }
        Update: {
          actor_id?: string | null
          body?: string
          category_id?: string | null
          created_at?: string
          data?: Json
          event_type?: string
          expires_at?: string | null
          id?: string
          is_read?: boolean
          push_error?: string | null
          push_receipt_id?: string | null
          push_status?: string
          push_ticket_id?: string | null
          read_at?: string | null
          recipient_id?: string
          route?: string | null
          sent_at?: string | null
          title?: string
        }
        Relationships: []
      }
      permissions: {
        Row: {
          created_at: string
          description: string | null
          key: string
          label: string
          section: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          key: string
          label: string
          section: string
        }
        Update: {
          created_at?: string
          description?: string | null
          key?: string
          label?: string
          section?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string | null
          expo_push_token: string | null
          full_name: string | null
          id: string
          is_active: boolean
          last_push_token_updated_at: string | null
          phone: string | null
          profile_type: string
          push_opt_in: boolean
          role: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          expo_push_token?: string | null
          full_name?: string | null
          id: string
          is_active?: boolean
          last_push_token_updated_at?: string | null
          phone?: string | null
          profile_type?: string
          push_opt_in?: boolean
          role?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string | null
          expo_push_token?: string | null
          full_name?: string | null
          id?: string
          is_active?: boolean
          last_push_token_updated_at?: string | null
          phone?: string | null
          profile_type?: string
          push_opt_in?: boolean
          role?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      property_leads: {
        Row: {
          created_at: string
          id: string
          inquirer_id: string
          message: string | null
          property_id: string
          status: string
        }
        Insert: {
          created_at?: string
          id?: string
          inquirer_id: string
          message?: string | null
          property_id: string
          status?: string
        }
        Update: {
          created_at?: string
          id?: string
          inquirer_id?: string
          message?: string | null
          property_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "property_leads_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "listing_moderation_queue"
            referencedColumns: ["id"]
          },
        ]
      }
      rbac_scopes: {
        Row: {
          created_at: string
          district_code: string | null
          id: string
          province_code: string | null
          scope_type: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          district_code?: string | null
          id?: string
          province_code?: string | null
          scope_type: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          district_code?: string | null
          id?: string
          province_code?: string | null
          scope_type?: string
          updated_at?: string
        }
        Relationships: []
      }
      role_permissions: {
        Row: {
          created_at: string
          permission_key: string
          role_key: string
        }
        Insert: {
          created_at?: string
          permission_key: string
          role_key: string
        }
        Update: {
          created_at?: string
          permission_key?: string
          role_key?: string
        }
        Relationships: [
          {
            foreignKeyName: "role_permissions_permission_key_fkey"
            columns: ["permission_key"]
            isOneToOne: false
            referencedRelation: "permissions"
            referencedColumns: ["key"]
          },
          {
            foreignKeyName: "role_permissions_role_key_fkey"
            columns: ["role_key"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["role_key"]
          },
        ]
      }
      roles: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          is_active: boolean
          is_system: boolean
          label: string
          role_key: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_active?: boolean
          is_system?: boolean
          label: string
          role_key: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_active?: boolean
          is_system?: boolean
          label?: string
          role_key?: string
          updated_at?: string
        }
        Relationships: []
      }
      support_ticket_messages: {
        Row: {
          body: string
          created_at: string
          id: string
          image_url: string | null
          message_type: string
          sender_id: string | null
          sender_role: string
          ticket_id: string
        }
        Insert: {
          body?: string
          created_at?: string
          id?: string
          image_url?: string | null
          message_type?: string
          sender_id?: string | null
          sender_role: string
          ticket_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          image_url?: string | null
          message_type?: string
          sender_id?: string | null
          sender_role?: string
          ticket_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_ticket_messages_ticket_id_fkey"
            columns: ["ticket_id"]
            isOneToOne: false
            referencedRelation: "support_tickets"
            referencedColumns: ["id"]
          },
        ]
      }
      support_tickets: {
        Row: {
          closed_at: string | null
          created_at: string
          id: string
          last_message_at: string
          priority: string
          status: string
          subject: string
          ticket_no: number
          updated_at: string
          user_id: string
        }
        Insert: {
          closed_at?: string | null
          created_at?: string
          id?: string
          last_message_at?: string
          priority?: string
          status?: string
          subject: string
          ticket_no?: never
          updated_at?: string
          user_id: string
        }
        Update: {
          closed_at?: string | null
          created_at?: string
          id?: string
          last_message_at?: string
          priority?: string
          status?: string
          subject?: string
          ticket_no?: never
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      user_blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_listing_favourites: {
        Row: {
          created_at: string
          listing_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          listing_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          listing_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_listing_favourites_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listing_moderation_queue"
            referencedColumns: ["id"]
          },
        ]
      }
      user_preferences: {
        Row: {
          category_code: string | null
          created_at: string
          max_price: number | null
          min_price: number | null
          preferred_amenities: string[] | null
          updated_at: string
          user_id: string
        }
        Insert: {
          category_code?: string | null
          created_at?: string
          max_price?: number | null
          min_price?: number | null
          preferred_amenities?: string[] | null
          updated_at?: string
          user_id: string
        }
        Update: {
          category_code?: string | null
          created_at?: string
          max_price?: number | null
          min_price?: number | null
          preferred_amenities?: string[] | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      user_recently_viewed: {
        Row: {
          id: string
          property_id: string
          user_id: string
          viewed_at: string
        }
        Insert: {
          id?: string
          property_id: string
          user_id: string
          viewed_at?: string
        }
        Update: {
          id?: string
          property_id?: string
          user_id?: string
          viewed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_recently_viewed_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "listing_moderation_queue"
            referencedColumns: ["id"]
          },
        ]
      }
      user_reports: {
        Row: {
          created_at: string
          id: string
          reason: string
          reported_id: string
          reporter_id: string
          status: string
        }
        Insert: {
          created_at?: string
          id?: string
          reason: string
          reported_id: string
          reporter_id: string
          status?: string
        }
        Update: {
          created_at?: string
          id?: string
          reason?: string
          reported_id?: string
          reporter_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_reports_reported_id_fkey"
            columns: ["reported_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_role_assignments: {
        Row: {
          assigned_by: string | null
          created_at: string
          id: string
          is_active: boolean
          role_key: string
          scope_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          assigned_by?: string | null
          created_at?: string
          id?: string
          is_active?: boolean
          role_key: string
          scope_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          assigned_by?: string | null
          created_at?: string
          id?: string
          is_active?: boolean
          role_key?: string
          scope_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_role_assignments_role_key_fkey"
            columns: ["role_key"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["role_key"]
          },
          {
            foreignKeyName: "user_role_assignments_scope_id_fkey"
            columns: ["scope_id"]
            isOneToOne: false
            referencedRelation: "rbac_scopes"
            referencedColumns: ["id"]
          },
        ]
      }
      user_search_history: {
        Row: {
          created_at: string
          filters: Json | null
          id: string
          query_text: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          filters?: Json | null
          id?: string
          query_text?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          filters?: Json | null
          id?: string
          query_text?: string | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      chat_room_summaries: {
        Row: {
          landlord_id: string | null
          last_message_content: string | null
          last_message_created_at: string | null
          last_message_id: string | null
          last_message_is_read: boolean | null
          last_message_sender_id: string | null
          last_message_type: string | null
          listing_id: string | null
          property_thumbnail: string | null
          property_title: string | null
          room_created_at: string | null
          room_id: string | null
          tenant_id: string | null
          updated_at: string | null
        }
        Relationships: [
          {
            foreignKeyName: "chat_messages_sender_id_fkey"
            columns: ["last_message_sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_rooms_landlord_id_fkey"
            columns: ["landlord_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_rooms_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listing_moderation_queue"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chat_rooms_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      create_notification_event: {
        Args: {
          p_actor_id: string
          p_body: string
          p_category_id: string
          p_data?: Json
          p_event_type: string
          p_expires_at?: string
          p_recipient_id: string
          p_route: string
          p_title: string
        }
        Returns: string
      }
      delete_my_account: { Args: never; Returns: undefined }
      get_app_explore_listings: {
        Args: {
          p_amenity_tags?: string[]
          p_category?: string
          p_district_id?: string
          p_limit?: number
          p_max_price?: number
          p_min_price?: number
          p_municipality_id?: string
          p_offset?: number
          p_state_id?: string
          p_subcategory?: string
          p_ward_id?: string
        }
        Returns: {
          amenity_tags: string[]
          currency_code: string
          district_id: string
          id: string
          is_featured: boolean
          landlord_is_verified: boolean
          listed_by: string
          location_text: string
          municipality_id: string
          photo_urls: string[]
          price: number
          property_category: string
          property_title: string
          state_id: string
          subcategory: string
          submitted_at: string
          thumbnail_url: string
          ward_id: string
        }[]
      }
      get_app_has_viewed_listing: {
        Args: { p_listing_id: string }
        Returns: boolean
      }
      get_app_home_listings: {
        Args: { p_limit?: number }
        Returns: {
          currency_code: string
          id: string
          is_featured: boolean
          landlord_is_verified: boolean
          location_text: string
          photo_urls: string[]
          price: number
          property_category: string
          property_title: string
          thumbnail_url: string
        }[]
      }
      get_app_listing_details: {
        Args: { p_listing_id: string }
        Returns: {
          amenity_tags: string[]
          carpet_area_sqft: number
          currency_code: string
          description: string
          district_id: string
          id: string
          is_negotiable: boolean
          is_featured: boolean
          is_story: boolean
          landlord_is_verified: boolean
          latitude: number | null
          listed_by: string
          location_text: string
          longitude: number | null
          municipality_id: string
          photo_urls: string[]
          price: number
          property_category: string
          property_floor_no: number
          property_title: string
          show_exact_location: boolean
          state_id: string
          subcategory: string
          submitted_at: string
          thumbnail_url: string
          total_area_sqft: number
          total_floor: number
          updated_at: string
          view_count: number
          ward_id: string
        }[]
      }
      get_app_listing_viewers: {
        Args: { p_listing_id: string }
        Returns: {
          email: string
          full_name: string
          last_viewed_at: string
          phone: string
          viewer_user_id: string
        }[]
      }
      get_app_property_leads: {
        Args: { p_listing_id?: string }
        Returns: {
          created_at: string
          id: string
          inquirer_email: string
          inquirer_id: string
          inquirer_name: string
          inquirer_phone: string
          listing_title: string
          message: string
          property_id: string
          status: string
        }[]
      }
      get_app_recently_viewed: {
        Args: { p_limit?: number; p_offset?: number }
        Returns: {
          amenity_tags: string[]
          currency_code: string
          district_id: string
          id: string
          is_featured: boolean
          landlord_is_verified: boolean
          listed_by: string
          location_text: string
          municipality_id: string
          photo_urls: string[]
          price: number
          property_category: string
          property_title: string
          state_id: string
          subcategory: string
          submitted_at: string
          thumbnail_url: string
          viewed_at: string
          ward_id: string
        }[]
      }
      get_app_recommended_listings: {
        Args: {
          p_amenity_tags?: string[]
          p_category?: string
          p_district_id?: string
          p_limit?: number
          p_max_price?: number
          p_min_price?: number
          p_municipality_id?: string
          p_offset?: number
          p_state_id?: string
          p_subcategory?: string
          p_user_lat?: number
          p_user_lng?: number
          p_user_radius_km?: number
          p_ward_id?: string
        }
        Returns: {
          amenity_tags: string[]
          currency_code: string
          district_id: string
          id: string
          is_featured: boolean
          landlord_is_verified: boolean
          listed_by: string
          location_text: string
          municipality_id: string
          photo_urls: string[]
          price: number
          property_category: string
          property_title: string
          state_id: string
          subcategory: string
          submitted_at: string
          thumbnail_url: string
          ward_id: string
        }[]
      }
      get_app_saved_listings: {
        Args: { p_limit?: number; p_offset?: number }
        Returns: {
          amenity_tags: string[]
          currency_code: string
          district_id: string
          favourited_at: string
          id: string
          is_featured: boolean
          landlord_is_verified: boolean
          location_text: string
          municipality_id: string
          photo_urls: string[]
          price: number
          property_category: string
          property_title: string
          state_id: string
          subcategory: string
          submitted_at: string
          thumbnail_url: string
          ward_id: string
        }[]
      }
      get_chat_messages_page: {
        Args: { p_page?: number; p_page_size?: number; p_room_id: string }
        Returns: {
          content: string
          created_at: string
          id: string
          is_read: boolean
          message_type: string
          room_id: string
          sender_id: string
        }[]
      }
      get_my_chat_rooms: {
        Args: never
        Returns: {
          counterparty_avatar_url: string
          counterparty_full_name: string
          counterparty_id: string
          landlord_id: string
          last_message_content: string
          last_message_created_at: string
          last_message_id: string
          last_message_is_read: boolean
          last_message_sender_id: string
          last_message_type: string
          listing_id: string
          property_thumbnail: string
          property_title: string
          room_created_at: string
          room_id: string
          tenant_id: string
          updated_at: string
        }[]
      }
      has_permission: {
        Args: { p_permission_key: string; p_user_id?: string }
        Returns: boolean
      }
      has_role: {
        Args: {
          p_district_code?: string
          p_province_code?: string
          p_role_key: string
          p_scope_type?: string
          p_user_id?: string
        }
        Returns: boolean
      }
      is_staff_user: { Args: { p_user_id?: string }; Returns: boolean }
      is_super_admin: { Args: { p_user_id?: string }; Returns: boolean }
      mark_all_notifications_read: { Args: never; Returns: undefined }
      record_listing_view: {
        Args: { p_listing_id: string; p_source?: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
